[programs.mainnet]
raffle = "FjZStEweLXQ7xkHHmQPchAkQ3zMz46b6JaWnoEdmSVRt"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "/home/ubuntu/apollo/test-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
